Repository KOSA-COTW/frontend, pull requests merged in 2025-08, with the labels that each got.

#10 fix: router 경로 수정
  src/router/index.js
Labels: fix

#13 fix: 회원 가입, 로그인 페이지 수정
  src/views/member/LoginView.vue
  src/views/member/SignupView.vue
Labels: fix

#22 feat: 게시글 라우트 분리 및 목록/노출 기능 개선
  src/components/Header.vue
  src/router/board.js
  src/router/index.js
  src/stores/auth.js
  src/stores/counter.js
  src/views/MainPage.vue
  src/views/board/PostDetailView.vue
  src/views/board/PostListView.vue
Labels: feat

#28 feat: 결제 취소 추가
  src/views/payment/PaymentHistoryView.vue
Labels: feat

#31 Feat/payment
  src/router/payment.js
  src/stores/payment.js
  src/utils/payment.js
  src/views/payment/MyPayments.vue
  src/views/payment/PaymentHistoryView.vue
  src/views/payment/SuccessView.vue
Labels: refactor

#32 feat: 탈퇴 버튼 추가
  src/views/member/MyPageView.vue
Labels: feat

#35 feat: 게시글 생성·수정 시 이미지 처리 기능 추가
  src/stores/post.js
  src/utils/post.js
  src/views/board/PostCreateView.vue
  src/views/board/PostDetailView.vue
  src/views/board/PostEditView.vue
Labels: feat

#36 Feat/payment
  src/views/board/PostDetailView.vue
  src/views/member/MyPageView.vue
Labels: feat

#38 fix: 기부내역 라우팅 오류 해결
  src/router/index.js
Labels: fix

#39 Feat/admin
  src/router/admin.js
  src/views/admin/donation/AdminDonationView.vue
  src/views/board/PostDetailView.vue
  src/views/member/MyPageLayoutView.vue
  src/views/member/MyPageView.vue
  src/views/payment/PaymentHistoryView.vue
Labels: feat, fix
